"""
Django settings for bank project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
from datetime import timedelta



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")
FIELD_ENCRYPTION_KEY = config('ENCRYPTION_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Set session expiry for admin users
SESSION_COOKIE_AGE = 3600  # Log out after 1 hr of inactivity (
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Log out when the browser closes
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = 'None'  # For cross-site cookies
CSRF_COOKIE_SAMESITE = 'None'  # For CSRF cookies if using CSRF protection
CSRF_COOKIE_SECURE = True  # Ensure CSRF cookie is sent over HTTPS set to true

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django_prometheus',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'analytics',
    'auth_service',
    'accounts',
    'notification',
    'transactions',
    'fraud_service',
    'ledger_service',
    'audit',
    'rest_framework',
    'corsheaders',
    'django_ckeditor_5',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'django_celery_beat',
    'defender',
    'drf_spectacular',
    'schema_viewer',
    'guardian',
    'django_daraja'
    

]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware", #handles static files like css for  admin dashboard
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', #should be below securitymiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",  
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'defender.middleware.FailedLoginMiddleware',  # Add Defender middleware
    'auth_service.middleware.SimpleAuditMiddleware',  # Audit logging middleware
    "django_prometheus.middleware.PrometheusAfterMiddleware", #should be last


]

ROOT_URLCONF = 'bank.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bank.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'bank_db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': config('POSTGRES_NAME'),  # Read DB_NAME from .env
#         'USER': config('POSTGRES_USER'),  # Read DB_USER from .env
#         'PASSWORD': config('POSTGRES_PASSWORD'),  # Read DB_PASSWORD from .env
#         'HOST': config('POSTGRES_HOST'),  # Read DB_HOST from .env
#         'PORT': 5432,  # Default PostgreSQL port
#         'OPTIONS': {
#             'sslmode': 'require',  # Enforce SSL encryption
#         },
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "auth_service.User"  # register the User table that will act as a connection between the diffrent user

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
    # for guardian permisisions
    'guardian.backends.ObjectPermissionBackend',

]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',

    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7), # in production update to 1 hr
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,  # Returns new refresh token on refresh
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,  # Update last login time on login
    'REFRESH_TOKEN_GRACE_PERIOD':timedelta(hours=1) # grace period for refresh token
}

FRONTEND_URL = "localhost:3000"

CELERY_BROKER_URL = f"{config('CELERY_BROKER_URL')}"  # DB 1 for Celery tasks
CELERY_RESULT_BACKEND = f"{config('CELERY_BROKER_URL')}"  # Same DB for results
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 10
CELERY_TASK_TRACK_STARTED = True  # Useful for progress tracking
CELERYD_MAX_MEMORY_PER_CHILD = 100000  # 100MB
CELERYD_MAX_TASKS_PER_CHILD = 50


SPECTACULAR_SETTINGS = {
    'TITLE': 'EverGreen Bank Documentation',
    'DESCRIPTION': 'Evergreeen management system',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    
    # OTHER SETTINGS
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,  
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "debug.log",
        },
    },
    "loggers": {
        "transactions": { 
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

MPESA_ENVIRONMENT = 'sandbox'
MPESA_CONSUMER_KEY = config("MPESA_CONSUMER_KEY")
MPESA_CONSUMER_SECRET = config("MPESA_CONSUMER_SECRET")
MPESA_SHORTCODE = config("MPESA_EXPRESS_SHORTCODE")
MPESA_PASSKEY = config("MPESA_PASSKEY")
MPESA_INITIATOR_USERNAME= config("MPESA_INITIATOR_USERNAME")
MPESA_INITIATOR_SECURITY_CREDENTIAL = config("MPESA_INITIATOR_SECURITY_CREDENTIAL")

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4000",
    "http://localhost:5173",
    "https://sandbox.safaricom.co.ke",
    "https://api.safaricom.co.ke",

]

CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",  # Allow custom Authorization headers
    "x-api-key",  # Allow X-Requested-With header (useful for AJAX requests)
    "accept",
    "ngrok-skip-browser-warning",
    "origin",
    "x-custom-header",  # Example of a custom header you'd like to allow
    "X-Frame-Options",  # Another example of a custom header
]
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = [
    "http://localhost:4000",  # Replace with your frontend URL
    "https://sandbox.safaricom.co.ke",
    "https://api.safaricom.co.ke",
    "196.201.214.200",
    "196.201.214.206",
    "196.201.213.114",
    "196.201.214.207",
    "196.201.214.208",
    "196.201.213.44",
    "196.201.212.127",
    "196.201.212.138",
    "196.201.212.129",
    "196.201.212.136",
    "196.201.212.74",
    "196.201.212.69"
    
]