"""Add mpesa_receipt_number to Transaction

Revision ID: 1d217f0622ca
Revises: 2ee1d79c7614
Create Date: 2024-08-25 00:56:56.525487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d217f0622ca'
down_revision = '2ee1d79c7614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_receipt_number', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('mpesa_receipt_number')

    # ### end Alembic commands ###
